baseURL: "https://yurukute.github.io/Blog/"
theme: PaperMod
publishDir: "docs"
defaultContentLanguage: vi
languages:
    vi:
        languageName: "Tiếng Việt"
        weight: 1
        title: Blog của Noob
        homeInfoParams:
            Title: "Chao xìn, mình là Noob OwO)/"
            Content: >
                Đây là blog đầu tay của Noob về cách giải mấy bài toán tin mà Noob gặp.

                - Noob viết cho vui.
            
                - Đừng bash Noob.
        menu:
            main:
                - name: Lưu trữ
                  url: /archive
                  weight: 5
                - name: Tìm kiếm
                  url: /search
                  weight: 7
                - name: Tags
                  url: /tags
                  weight: 8        
    en:
        languageName: "English"
        weight: 2
        title: Noob's Blog
        homeInfoParams:
            Title: "Hi there, I'm Noob OwO)/"
            Content: >
                This is Noob's first blog about how she solve programing problems that she has met.

                - Noob writes for fun
        
                - Don't bash Noob
        menu:
            main:
                - name: Archives
                  url: archive/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 7
                - name: Tags
                  url: tags/
                  weight: 8
params:
    socialIcons:
        - name: hackerrank
          url: "https://www.hackerrank.com/yurukute"
        - name: codewars
          url: "https://www.codewars.com/users/yurukute"
    ShowPostNavLinks: true
outputs:
    home:
        - HTML
        - RSS
        - JSON 
